# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd server
      - npm install
      - cd ..
      - cd clients
      - cd webclient
      - npm install
      - cd ..
      - cd ..
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - cd clients
      - cd webclient
      - npm run build
      - cd ..
      - cd ..
      - cd server
      - npx sls deploy
  post_build:
    commands:
      - echo Build completed on `date`
